### ISSUE TITLE
Cannot create datastore for Azure DataLake gen2  storage accounts

### ISSUE THREAD

**Issue by gdippolito** [orobix/terraform-provider-azureml#18]
Hi thanks for creating this proejct. I think it was very much needed to better organise datastore resources in AzureML since there is no support from the main provider. :pray: 

I spot a problem when trying to create a datastore from an Azure datalake Gen 2 storage account. 

These are the details

### Terraform Version
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.22.0
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
+ provider registry.terraform.io/hashicorp/random v3.1.3
+ provider registry.terraform.io/telemaco019/azureml v0.0.1

### Affected Resource(s)
- azureml_datastore

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "azureml_datastore" "dataset" {
  resource_group_name = var.workspace_rg
  workspace_name         = var.workspace_name
  name                            = "example"
  description                   = "${var.workspace_name}-description"
  storage_type        = "AzureBlob"

  storage_account_name   = var.datasource_storage_account_name
  storage_container_name = "dataset"

  auth {
    credentials_type = "ServicePrincipal"
    client_id         = var.service_principal_id
    client_secret  = var.service_principal_password
    tenant_id       = var.tenant_id
  }
}
```

### Expected Behavior
datastore created successfully 

### Actual Behavior
```
│ Error: HTTP Response is in error [status code 400]: {
│   "error": {
│     "code": "UserError",
│     "message": "Request is invalid and/or missing fields.",
│     "details": [
│       {
│         "code": "RequestInvalid",
│         "message": "The Endpoint field is required.",
│         "details": [],
│         "additionalInfo": []
│       },
│       {
│         "code": "RequestInvalid",
│         "message": "The Protocol field is required.",
│         "details": [],
│         "additionalInfo": []
│       }
│     ],
│     "additionalInfo": [
│       {
│         "type": "ComponentName",
│         "info": {
│           "value": "managementfrontend"
│         }
│       },
│       {
│         "type": "Correlation",
│         "info": {
│           "value": {
│             "operation": "55689d8e612b6f4194a496f223bcd7d8",
│             "request": "22a3d1a23ab48614"
│           }
│         }
│       },
│       {
│         "type": "Environment",
│         "info": {
│           "value": "eastus"
│         }
│       },
│       {
│         "type": "Location",
│         "info": {
│           "value": "eastus"
│         }
│       },
│       {
│         "type": "Time",
│         "info": {
│           "value": "2022-05-06T13:01:04.6783409+00:00"
│         }
│       },
│       {
│         "type": "InnerError",
│         "info": {
│           "value": {
│             "code": "RequestInvalid",
│             "innerError": null
│           }
│         }
│       },
│       {
│         "type": "MessageFormat",
│         "info": {
│           "value": "Request is invalid and/or missing fields."
│         }
│       }
│     ]
│   }
│ }
```

### Steps to Reproduce
`terraform apply`

### Note

I suspect the error is due to

**Comment by Telemaco019** [comment]
Hi @gdippolito, the problem should be fixed with version 0.0.4. You can install it as follows:
```
required_providers {
    azureml = {
      source  = "registry.terraform.io/orobix/azureml"
      version = "0.0.3"
    }
}
```

**Comment by gdippolito** [comment]
Thanks for the response! 

We did try this today and I think there is some validation still not working for our storage account. See the error below:
```
 Error: HTTP Response is in error [status code 400]: {
│   "error": {
│     "code": "UserError",
│     "message": "Missing discriminator property [DatastoreType] in request body.",
│     "details": [],
│     "additionalInfo": [
│       {
│         "type": "ComponentName",
│         "info": {
│           "value": "managementfrontend"
│         }
│       },
│       {
│         "type": "Correlation",
│         "info": {
│           "value": {
│             "operation": "9245581e12159a4fab14a15c8ebb3e88",
│             "request": "75da9f1270cd6a4f"
│           }
│         }
│       },
│       {
│         "type": "Environment",
│         "info": {
│           "value": "eastus"
│         }
│       },
│       {
│         "type": "Location",
│         "info": {
│           "value": "eastus"
│         }
│       },
│       {
│         "type": "Time",
│         "info": {
│           "value": "2022-05-09T15:13:03.8164097+00:00"
│         }
│       },
│       {
│         "type": "InnerError",
│         "info": {
│           "value": {
│             "code": "BadData",
│             "innerError": {
│               "code": "UnableToParse",
│               "innerError": {
│                 "code": "JsonDiscriminatorMissing",
│                 "innerError": null
│               }
│             }
│           }
│         }
│       },
│       {
│         "type": "MessageFormat",
│         "info": {
│           "value": "Missing discriminator property [{discriminatorName}] in request body."
│         }
│       },
│       {
│         "type": "MessageParameters",
│         "info": {
│           "value": {
│             "discriminatorName": "DatastoreType"
│           }
│         }
│       }
│     ]
│   }
│ }
```
Terraform version:
```
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.22.0
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
+ provider registry.terraform.io/hashicorp/random v3.1.3
+ provider registry.terraform.io/orobix/azureml v0.0.4
```
Module invocation:
```
resource "azureml_datastore" "dataset" {
  resource_group_name = var.workspace_rg
  workspace_name      = var.workspace_name
  name                = "ds-dataset"
  description         = "${var.workspace_name}-dataset datastore"
  storage_type        = "AzureBlob"

  storage_account_name   = var.datasource_storage_account_name
  storage_container_name = "dataset"

  auth {
    credentials_type = "ServicePrincipal"
    client_id        = var.service_principal_id
    client_secret    = var.service_principal_password
    tenant_id        = var.tenant_id
  }
}
```

Would this error make sense to you? Thanks!

**Comment by Telemaco019** [comment]
Some mandatory fields were not provided in the POST calls for creating the datastore (I guess Azure made them mandatory recently). Release v0.0.5 of the provider fixes this problem, thank you for reporting the issue!

**Comment by gdippolito** [comment]
Thanks! That worked.
